export const poiStyles = {
  itemContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
    marginBottom: '0.85rem',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.82rem',
  },
  titleText: {
    fontWeight: '600',
    color: '#16212B',
  },
  nameText: {
    fontSize: '0.78rem',
    color: '#52606B',
  },
  distanceText: {
    fontWeight: '700',
    fontSize: '0.82rem',
  },
  track: {
    width: '100%',
    height: '6px',
    backgroundColor: '#E5E7EB',
    borderRadius: '999px',
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.4s ease',
  },
};

export const styles = {
  pageContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '1.2rem 1.5rem 4rem',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#16212B',
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.5rem',
  },
  title: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '2.1rem',
    fontWeight: '600',
    color: '#16212B',
    margin: '0 0 0.35rem 0',
  },
  subtitle: {
    fontSize: '0.92rem',
    color: '#52606B',
    maxWidth: '580px',
    margin: '0 auto',
    lineHeight: '1.4',
  },
  errorBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    backgroundColor: '#FBEAE7',
    border: '1px solid #F1DAD3',
    color: '#8A3226',
    padding: '0.85rem 1.25rem',
    borderRadius: '10px',
    fontSize: '0.88rem',
    marginBottom: '1.5rem',
  },
  mainLayout: {
    display: 'grid',
    gridTemplateColumns: '1.1fr 0.9fr',
    gap: '2rem',
    alignItems: 'start',
  },
  formCard: {
    backgroundColor: '#FFFDF9',
    border: '1px solid #E7DFCD',
    borderRadius: '16px',
    padding: '1.75rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.03)',
    boxSizing: 'border-box',
    width: '100%',
  },
  sectionBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  sectionTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '1.05rem',
    fontWeight: '600',
    color: '#16212B',
    margin: 0,
  },
  divider: {
    border: 'none',
    borderTop: '1px solid #E7DFCD',
    margin: '1.15rem 0',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
    width: '100%',
    boxSizing: 'border-box',
  },
  label: {
    fontSize: '0.8rem',
    fontWeight: '600',
    color: '#52606B',
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '0.65rem 0.85rem',
    borderRadius: '8px',
    border: '1px solid #D8CDB8',
    fontSize: '0.92rem',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    color: '#16212B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
  },
  selectInput: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '0.7rem 0.85rem',
    borderRadius: '8px',
    border: '1px solid #D8CDB8',
    fontSize: '0.92rem',
    fontWeight: '500',
    color: '#16212B',
    backgroundColor: '#FFFFFF',
    outline: 'none',
    cursor: 'pointer',
  },
  inputError: {
    borderColor: '#B33F30 !important',
  },
  errorText: {
    fontSize: '0.75rem',
    color: '#B33F30',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '1rem',
  },
  pillsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
  },
  pill: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.7rem',
    borderRadius: '10px',
    border: '1px solid #E7DFCD',
    backgroundColor: '#F9F6EE',
    color: '#52606B',
    fontSize: '0.85rem',
    fontWeight: '500',
    cursor: 'pointer',
    userSelect: 'none',
  },
  pillActive: {
    backgroundColor: '#EAF2F1',
    borderColor: '#0F766E',
    color: '#0F766E',
    fontWeight: '600',
  },
  dropZone: {
    border: '2px dashed #D8CDB8',
    borderRadius: '12px',
    padding: '1.1rem',
    backgroundColor: '#FAF8F5',
    textAlign: 'center',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
  },
  dropZoneActive: {
    borderColor: '#0F766E',
    backgroundColor: '#EAF2F1',
  },
  uploadLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.85rem',
    cursor: 'pointer',
  },
  uploadIconCircle: {
    width: '38px',
    height: '38px',
    borderRadius: '50%',
    backgroundColor: '#EAF2F1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  previewsGrid: {
    display: 'flex',
    gap: '0.6rem',
    flexWrap: 'wrap',
    marginTop: '0.5rem',
  },
  previewThumbWrapper: {
    position: 'relative',
    width: '60px',
    height: '60px',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #D8CDB8',
  },
  previewThumb: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  removeBtn: {
    position: 'absolute',
    top: '3px',
    right: '3px',
    backgroundColor: 'rgba(179, 63, 48, 0.85)',
    border: 'none',
    borderRadius: '50%',
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
  },
  actionsRow: {
    display: 'flex',
    gap: '0.75rem',
    marginTop: '1.5rem',
  },
  submitBtn: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    backgroundColor: '#0F766E',
    color: '#FFFFFF',
    border: 'none',
    padding: '0.85rem',
    borderRadius: '10px',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
  },
  clearBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    backgroundColor: '#F3EFE6',
    color: '#52606B',
    border: '1px solid #E7DFCD',
    padding: '0.85rem 1.25rem',
    borderRadius: '10px',
    fontSize: '0.88rem',
    fontWeight: '600',
    cursor: 'pointer',
  },

  /* 🌟 Onboarding Panel Styles */
  previewColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  previewHeroCard: {
    backgroundColor: '#FFFDF9',
    border: '1px solid #E7DFCD',
    borderRadius: '16px',
    padding: '1.75rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.02)',
  },
  previewHeroTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '1.2rem',
    fontWeight: '600',
    color: '#16212B',
    margin: '0 0 0.5rem 0',
  },
  previewHeroText: {
    fontSize: '0.86rem',
    color: '#52606B',
    lineHeight: '1.5',
    margin: '0 0 1.25rem 0',
  },
  statsMiniRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
    marginBottom: '1.5rem',
  },
  statMiniBox: {
    backgroundColor: '#F9F6EE',
    padding: '0.75rem',
    borderRadius: '10px',
    border: '1px solid #E7DFCD',
  },
  statMiniLabel: {
    fontSize: '0.72rem',
    color: '#7A7264',
    display: 'block',
    marginBottom: '0.2rem',
  },
  statMiniValue: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#0F766E',
  },
  featureCardsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  featureCardItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.85rem',
    padding: '0.85rem',
    backgroundColor: '#FAF8F5',
    border: '1px solid #E7DFCD',
    borderRadius: '12px',
  },
  featureCardIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: '#EAF2F1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: '2px',
  },
  featureCardTitle: {
    fontSize: '0.86rem',
    fontWeight: '700',
    color: '#16212B',
    marginBottom: '0.2rem',
  },
  featureCardDesc: {
    fontSize: '0.78rem',
    color: '#52606B',
    lineHeight: '1.4',
    margin: 0,
  },

  /* Results Section */
  resultsColumn: {
    height: '100%',
  },
  resultsWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.1rem',
  },
  mainEstimateCard: {
    backgroundColor: '#0F766E',
    backgroundImage: 'linear-gradient(135deg, #0F766E 0%, #163846 100%)',
    color: '#FFFFFF',
    borderRadius: '18px',
    padding: '1.75rem',
    boxShadow: '0 12px 30px rgba(15,118,110,0.22)',
  },
  cardHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  mainEstimateLabel: {
    display: 'flex',
    alignItems: 'center',
    fontSize: '0.75rem',
    fontWeight: '700',
    letterSpacing: '1px',
    color: '#A7F3D0',
  },
  accuracyTag: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    padding: '0.2rem 0.6rem',
    borderRadius: '999px',
    fontSize: '0.72rem',
    fontWeight: '600',
  },
  priceContainer: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '0.2rem',
    margin: '0.5rem 0 1rem',
  },
  currencySymbol: {
    fontSize: '1.8rem',
    fontWeight: '600',
    color: '#A7F3D0',
  },
  mainEstimateNumber: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '3.2rem',
    fontWeight: '700',
    lineHeight: 1,
  },
  perMonthLabel: {
    fontSize: '0.95rem',
    opacity: 0.8,
    marginLeft: '0.3rem',
  },
  rangeRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.75rem',
    flexWrap: 'wrap',
  },
  rangePill: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    padding: '0.4rem 0.85rem',
    borderRadius: '8px',
    fontSize: '0.8rem',
  },
  sqmPill: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    padding: '0.4rem 0.85rem',
    borderRadius: '8px',
    fontSize: '0.8rem',
  },
  askingComparisonBox: {
    marginTop: '1.25rem',
    padding: '0.75rem 1rem',
    borderRadius: '12px',
    border: '1px solid',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  visionCard: {
    backgroundColor: '#FFFDF9',
    border: '1px solid #C5E0DC',
    borderRadius: '16px',
    padding: '1.25rem',
    boxShadow: '0 4px 15px rgba(15, 118, 110, 0.05)',
  },
  visionCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.85rem',
    borderBottom: '1px solid #E7DFCD',
    paddingBottom: '0.65rem',
  },
  visionTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '0.98rem',
    fontWeight: '600',
    color: '#16212B',
    margin: 0,
  },
  visionScoreBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    backgroundColor: '#FBF3E8',
    color: '#8A5D20',
    padding: '0.3rem 0.65rem',
    borderRadius: '999px',
    fontSize: '0.82rem',
    fontWeight: '700',
  },
  loaderContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.2rem 1rem',
    backgroundColor: '#FAF8F5',
    borderRadius: '12px',
    border: '1px dashed #D8CDB8',
  },
  visionBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.85rem',
  },
  visionSummaryText: {
    fontSize: '0.88rem',
    lineHeight: '1.5',
    color: '#16212B',
    margin: 0,
    backgroundColor: '#F9F6EE',
    padding: '0.75rem',
    borderRadius: '8px',
    borderLeft: '3px solid #0F766E',
  },
  visionListBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  listBlockTitle: {
    fontSize: '0.78rem',
    fontWeight: '700',
    color: '#52606B',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  visionList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  visionListItemPositive: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    fontSize: '0.82rem',
    color: '#16212B',
    lineHeight: '1.4',
  },
  visionListItemObservation: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    fontSize: '0.82rem',
    color: '#52606B',
    lineHeight: '1.4',
  },
  valueScoreCard: {
    backgroundColor: '#FFFDF9',
    border: '1px solid #E7DFCD',
    borderRadius: '14px',
    padding: '1.25rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.65rem',
  },
  valueScoreHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  valueScoreTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#16212B',
  },
  valueScoreBadge: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '1.2rem',
    fontWeight: '700',
    color: '#16212B',
  },
  progressBarTrack: {
    width: '100%',
    height: '8px',
    backgroundColor: '#E5E7EB',
    borderRadius: '999px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.5s ease',
  },
  dealTypeLabel: {
    fontSize: '0.82rem',
    color: '#52606B',
  },
  infoCard: {
    backgroundColor: '#FFFDF9',
    border: '1px solid #E7DFCD',
    borderRadius: '14px',
    padding: '1.1rem 1.25rem',
  },
  cardHeaderFlex: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    marginBottom: '0.85rem',
  },
  infoCardTitle: {
    fontFamily: "'Fraunces', Georgia, serif",
    fontSize: '0.92rem',
    fontWeight: '600',
    color: '#16212B',
    margin: 0,
  },
  poiBarsContainer: {
    display: 'flex',
    flexDirection: 'column',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
  },
  statBox: {
    backgroundColor: '#F9F6EE',
    padding: '0.7rem 0.85rem',
    borderRadius: '10px',
    border: '1px solid #E7DFCD',
  },
  statLabel: {
    display: 'block',
    fontSize: '0.72rem',
    color: '#7A7264',
    marginBottom: '0.15rem',
  },
  statValue: {
    fontSize: '1.05rem',
    fontWeight: '700',
    color: '#16212B',
  },
  reasonsWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  reasonTag: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.6rem 0.85rem',
    borderRadius: '8px',
    fontSize: '0.82rem',
    fontWeight: '500',
  },
};